
version: "3"

services:
  database:
    image: postgres:latest
    networks:
      - backend
    environment:
      - POSTGRESQL_USER=neuro
      - POSTGRESQL_PASSWORD=neuropass
      - POSTGRESQL_DATABASE=neurodb
      - POSTGRESQL_ADMIN_PASSWORD=neuropass
    volumes:
      - './data/postgres:/var/lib/pgsql/data'
    restart: always

volumes:
  static-files:
  customization:

networks:
  backend:
  frontend:
